### ISSUE TITLE
feat: Enable the system to use rtc by default

### ISSUE THREAD

**Issue by sanni-t** [Opentrons/buildroot#126]
Once the device tree & driver for the new RTC are built, we will need to make sure that:
- [ ] a robot with the updated OS recognizes the RTC at boot and loads its drivers (i2c & rtc)
- [ ] the robot is able to write to the RTC (through some provisioning process outside the scope of this ticket)
- [ ] After provisioning, the robot reads from the RTC on each boot (preferably very early on in the boot process)

**Comment by mcous** [comment]
Closed by #129
