### ISSUE TITLE
docs: add maintainer guide for adding and updating Python packages

### ISSUE THREAD

**Issue by mcous** [Opentrons/buildroot#136]
## Overview

#131 has been a real adventure, and I ran into several gotchas related to adding and updating Python packages. These learnings need to be added to documentation so we don't have to repeat this.

## Notes

- Always check upstream first; the work's sometimes been done for you
- Add instructions on how to use `utils/scanpypi`
    - Also, I ran into a bug in that script
    - Note to self: check upstream for an update
- Be prepared to read into pacakge's `setup.py` (or whatever) to learn about how it's built
    - Also be prepared to cherry-pick a setuptools update from upstream if you find it needs a newer version
- Many packages require setuptools plugins, add them to `python-foo.mk`
    - e.g. `setuptools-scm` and `setuptools-scm[toml]` is a common plugin, add it with:
    - `PYTHON_FOO_DEPENDENCIES = host-python-setuptools-scm host-python-toml`
- Even if the build completes, inspect `output/target/lib/python3.7/site-packages` to make sure version numbers were picked up correctly
    - You may see `package-name-0.0.0` if the build plugins (see above) weren't available
    - If you don't have a local build set up, I think you can do the same thing on the OT-2's filesystem after boot

**Comment by SyntaxColoring** [comment]
Replaced by RSS-54.
