### ISSUE TITLE
Upgrade robot-server dependencies

### ISSUE THREAD

**Issue by mcous** [Opentrons/buildroot#160]
This is a companion ticket for Opentrons/opentrons#10701, Opentrons/opentrons#10702, and Opentrons/opentrons#10704.

We need to upgrade the following Python runtime dependencies

- [ ] typing-extensions
- [ ] pydantic
- [ ] fastapi
- [ ] anyio
- [ ] starlette

**Comment by SyntaxColoring** [comment]
Moved to RSS-50.
