### ISSUE TITLE
Feature request: Ship pandas with the Robot OS

### ISSUE THREAD

**Issue by mcous** [Opentrons/buildroot#61]
We have a history of customer requests to use [pandas](https://pandas.pydata.org/) on the OT-2. For example, Opentrons/opentrons#4637 

pandas is prohibitively difficult to install on an OT-2 by a given end-user, but we would be able to ship it as part of our pre-installed stack. We should explore this option and potentially do it

**Comment by jcs-encodia** [comment]
Are there any easy ways to install pandas? I'm trying to read a CSV into the instrument but did not realize that it was not equipped! 

Are there any other work arounds?
Best,

Jerome

**Comment by mcous** [comment]
@jcs-encodia pandas will be included as part of the next software update (3.16), which should be released sometime in the next few weeks

**Comment by jcs-encodia** [comment]
Awesome! Thank you for getting back to me Mike.


Best,

Jerome
