### ISSUE TITLE
Eventlog causes hang in build

### ISSUE THREAD

**Issue by theosanderson** [Opentrons/buildroot#87]
When I cloned these (added a small number of packages, but I don't think that's relevant) and invoked `opentrons_build.sh` the build eventually hung while attempting to download https://my.balabit.com/downloads/eventlog/0.2/eventlog_0.2.12.tar.gz`. Balabit appears to no longer exist: https://www.balabit.com/ . It looks like eventlog has now been removed upstream: https://github.com/buildroot/buildroot/commit/5e0b1f9c2386e9184256b10ca19a6a7e4f4865cc, with syslog-ng updated to remove the dependency. I have applied that change and am now seeing whether it resolves the issue. I'll try to make a PR in due course but wanted to record the issue.

I did add some other packages at the same time but AFAICS, Syslog-ng is in the OT2 build and cannot be built without this now removed URL.

Not asking for any change at the moment, just recording my experience

**Comment by theosanderson** [comment]
I belatedly realise this may just be a brief outage to that site

**Comment by theosanderson** [comment]
I was able to build successfully with https://github.com/theosanderson/buildroot/commit/8b0a5c32fd45c8e39db8070a4a9237611e534b1e (obviously a few package additions that you don't want to merge there too)

**Comment by sfoster1** [comment]
@theosanderson could you link me to the upstream removal? I can cherry-pick it from there. We're not seeing the problem affect our builds so it might have just been a brief outage (a somewhat common and very frustrating buildroot problem)

**Comment by theosanderson** [comment]
The removal is: https://github.com/buildroot/buildroot/commit/5e0b1f9c2386e9184256b10ca19a6a7e4f4865cc (linked in OP). That breaks syslog-ng on its own (due to an unnecessary dependency). To resolve that I manually deleted the syslog-ng package and copied in the contents of the package from the current buildroot branch. Sorry that I don't have a good commit for the latter. No pressure from me to deal with this right now, just documenting my experience.

**Comment by theosanderson** [comment]
By the way, apart from this minor issue (and the sig check thing https://github.com/Opentrons/buildroot/pull/89)building went beautifully and was much less scary than I had feared -- thanks for the encouragement and for making it so smooth!

**Comment by sfoster1** [comment]
Any time! I'm glad to hear about it going so well. I might have to do some upstream archaeology, presumably there should be a commit somewhere that updates syslog-ng. Thanks for looking into this!

**Comment by mcous** [comment]
@theosanderson have you continued to experience these build failures? I don't think I've been able to reproduce, so if we're not seeing anything weird these days I might close this out

**Comment by theosanderson** [comment]
Hmm.. this was still happening for me many months later and I'd be suprised if it had resolved itself given that the domain is now dead (it wouldn't be reproducible if the files were cached locally). I'll give it another try very soon!

**Comment by theosanderson** [comment]
It worked! I promise it used to be reproducible :) Thanks
